name: Lint configuration files

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]
    branches-ignore:
      - main

jobs:
  lint:
    name: Lint configuration files
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: "1.0.0"
      - name: Lint the config files 🧹
        run: bun lint
